# Generated by Django 6.0.7 on 2026-07-20 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المشروع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('category', models.CharField(choices=[('مياه وآبار', 'مياه وآبار'), ('مساجد', 'مساجد'), ('زكاة مال', 'زكاة مال'), ('زكاة فطر', 'زكاة فطر'), ('فدية صيام', 'فدية صيام'), ('دعم التعليم', 'دعم التعليم'), ('الصحة', 'الصحة')], max_length=50, verbose_name='التصنيف')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المستهدف')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المجموع')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='رابط الصورة')),
                ('creator_name', models.CharField(blank=True, max_length=150, verbose_name='اسم المنشئ')),
                ('is_public', models.BooleanField(default=True, verbose_name='عام')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('donor_count', models.PositiveIntegerField(default=0, verbose_name='عدد المتبرعين')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان المشروع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('donor_name', models.CharField(blank=True, default='متبرع', max_length=150, verbose_name='اسم المتبرع')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='مجهول')),
                ('status', models.CharField(choices=[('success', 'ناجح'), ('pending', 'قيد الانتظار'), ('failed', 'فشل')], default='success', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التبرع')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='المتبرع')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='charity.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'تبرع',
                'verbose_name_plural': 'التبرعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
