# Generated by Django 6.0.7 on 2026-07-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(default='تبرع عام', max_length=100, verbose_name='نوع التبرع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('donor_name', models.CharField(blank=True, default='فاعل خير', max_length=150, verbose_name='اسم المتبرع')),
                ('receipt_image', models.TextField(blank=True, verbose_name='صورة الإشعار (base64)')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'تبرع بنكي مباشر',
                'verbose_name_plural': 'التبرعات البنكية المباشرة',
                'ordering': ['-created_at'],
            },
        ),
    ]
