# Generated by Django 6.0.7 on 2026-07-20 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_directdonation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(blank=True, verbose_name='النص')),
                ('link_url', models.URLField(blank=True, verbose_name='رابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='يبدأ في')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150, verbose_name='اسم البنك')),
                ('account_name', models.CharField(blank=True, max_length=150, verbose_name='اسم الحساب')),
                ('account_number', models.CharField(max_length=80, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('branch', models.CharField(blank=True, max_length=150, verbose_name='الفرع')),
                ('currency', models.CharField(default='SDG', max_length=20, verbose_name='العملة')),
                ('instructions', models.TextField(blank=True, verbose_name='تعليمات التحويل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الحساب الرئيسي')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
                'ordering': ['sort_order', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True, verbose_name='المعرّف')),
                ('icon', models.CharField(blank=True, help_text='اسم أيقونة lucide مثل Droplets أو Heart', max_length=50, verbose_name='أيقونة (اختياري)')),
                ('color', models.CharField(blank=True, default='text-emerald-600', max_length=40, verbose_name='لون CSS')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='الهاتف')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('read', 'مقروء'), ('replied', 'تم الرد'), ('archived', 'مؤرشف')], default='new', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='مثال: about, terms, privacy', max_length=80, unique=True, verbose_name='المفتاح')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفحة محتوى',
                'verbose_name_plural': 'صفحات المحتوى',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='الجسد الواحد', max_length=120, verbose_name='اسم المنصة')),
                ('tagline', models.CharField(blank=True, default='معاً لنصنع أثراً', max_length=255, verbose_name='الشعار المختصر')),
                ('about_text', models.TextField(blank=True, verbose_name='نبذة عن المنصة')),
                ('mission', models.TextField(blank=True, verbose_name='الرسالة')),
                ('vision', models.TextField(blank=True, verbose_name='الرؤية')),
                ('hero_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان الصفحة الرئيسية')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='وصف الصفحة الرئيسية')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد للتواصل')),
                ('contact_phone', models.CharField(blank=True, max_length=40, verbose_name='هاتف التواصل')),
                ('whatsapp_number', models.CharField(blank=True, default='249920380318', max_length=40, verbose_name='رقم واتساب')),
                ('facebook_url', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('twitter_url', models.URLField(blank=True, verbose_name='تويتر / X')),
                ('instagram_url', models.URLField(blank=True, verbose_name='إنستغرام')),
                ('logo_url', models.URLField(blank=True, verbose_name='رابط الشعار')),
                ('footer_text', models.CharField(blank=True, default='صنع بحب لأجل السودان', max_length=255, verbose_name='نص التذييل')),
                ('stats_donors', models.CharField(blank=True, default='5,000+', max_length=40, verbose_name='إحصائية المتبرعين')),
                ('stats_projects', models.CharField(blank=True, default='1,200+', max_length=40, verbose_name='إحصائية المشاريع')),
                ('stats_states', models.CharField(blank=True, default='18', max_length=40, verbose_name='إحصائية الولايات')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات المنصة',
                'verbose_name_plural': 'إعدادات المنصة',
            },
        ),
        migrations.AddField(
            model_name='directdonation',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AddField(
            model_name='directdonation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد المتبرع'),
        ),
        migrations.AddField(
            model_name='directdonation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='هاتف المتبرع'),
        ),
        migrations.AddField(
            model_name='directdonation',
            name='receipt_file',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='ملف الإشعار'),
        ),
        migrations.AddField(
            model_name='directdonation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='directdonation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfers', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة'),
        ),
        migrations.AddField(
            model_name='directdonation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='donation',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, default='منصة', max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='project',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/', verbose_name='صورة المشروع'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز في الرئيسية'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=150, verbose_name='الموقع / الولاية'),
        ),
        migrations.AlterField(
            model_name='directdonation',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('success', 'ناجح'), ('pending', 'قيد الانتظار'), ('failed', 'فشل'), ('refunded', 'مسترد')], db_index=True, default='success', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(db_index=True, max_length=80, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='directdonation',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='charity.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='project',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='charity.category', verbose_name='التصنيف (مرجع)'),
        ),
    ]
