# Generated by Django 6.0.7 on 2026-07-21 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_admin_cms_expand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project_pending', 'مشروع بانتظار الموافقة'), ('donation_pending', 'تبرع بانتظار التحقق'), ('transfer_pending', 'تحويل بنكي بانتظار المراجعة'), ('contact', 'رسالة تواصل'), ('system', 'نظام')], db_index=True, default='system', max_length=40, verbose_name='النوع')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(blank=True, verbose_name='الرسالة')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='رابط')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='مقروء')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرّف مرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إشعار إدارة',
                'verbose_name_plural': 'إشعارات الإدارة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='directdonation',
            name='amount_applied',
            field=models.BooleanField(default=False, verbose_name='أُضيف للمشروع'),
        ),
        migrations.AddField(
            model_name='directdonation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_donations', to='charity.project', verbose_name='المشروع (اختياري)'),
        ),
        migrations.AddField(
            model_name='donation',
            name='amount_applied',
            field=models.BooleanField(default=False, verbose_name='أُضيف للمشروع'),
        ),
        migrations.AddField(
            model_name='donation',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_donations', to='charity.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='هاتف المتبرع'),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_file',
            field=models.ImageField(blank=True, null=True, upload_to='donation_receipts/%Y/%m/', verbose_name='ملف الإشعار'),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_image',
            field=models.TextField(blank=True, verbose_name='صورة الإشعار (base64)'),
        ),
        migrations.AddField(
            model_name='donation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='donation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_donations', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, default='تحويل بنكي', max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد التحقق'), ('success', 'تم التحقق'), ('failed', 'مرفوض'), ('refunded', 'مسترد')], db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('inactive', 'موقوف'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
